name: Release Binaries

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags (e.g., v1.0.0)
    workflow_dispatch: # Allow manual trigger

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 3: Build the binary
      - name: Build binary
        run: cargo build --release

      # Step 4: Upload the binary as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/lrg_backend
          asset_name: lrg_backend
          asset_content_type: application/octet-stream

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Create a release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
